apiVersion: v1
kind: PersistentVolume
metadata:
  name: geoserver-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/hosthome/tarter/GIS/geonode/K8/geoserver/data_osgeolive/"
