apiVersion: v1
kind: PersistentVolume
metadata:
  name: osm-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/hosthome/tarter/osm_data/"
